### ISSUE TITLE
Add /metrics endpoint

### ISSUE THREAD

**Issue by toni-sissala** [cessda/cessda.cdc.aggregator.oai-pmh-repo-handler#43]
Requested by CESSDA MO at 

https://github.com/cessda/cessda.cdc.versions/issues/446#issuecomment-1534226217

Copied here for reference

Metrics to instrument for are:

Inclusion of Service Provider Records Metrics:
* Number of Publishers (Service Providers) included
* Number of records included per Publisher
* Inclusion success rate per Publisher
* Inclusion failure rate per Publisher
* Total number of records included
* Average inclusion success rate
* Average inclusion failure rate

Harvesting by External Catalogue (Aggregators) Metrics:
* Number of publishers requested (should be the same as the number of publishers included, but interesting if not)
* Number of external catalogue requests received per Aggregator
* Total number of external catalogue requests received
* Number of successful external catalogue requests
* Number of unsuccessful external catalogue requests
* Average time taken to harvest records from an external catalogue request

These metrics can be instrumented using Prometheus and exposed at /metrics endpoint. For example, using the [prometheus_client library](https://github.com/prometheus/client_python) in Python:

**Comment by toni-sissala** [comment]
Requesting feedback from @matthew-morris-cessda 

### I have implemented the following metrics:

**Number of Publishers (Service Providers) included**

Result is calculated by querying Document Store for distinct OAI-PMH base url values in source documents. Only base urls which are direct sources are included, meaning that if CESSDA should harvest another aggregator, only that aggregator's base url is included in resulting number. Records that are logically deleted (http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords) are included in this number.

Response body example:

```
# HELP publishers_total Total number of distinct publishers
# TYPE publishers_total gauge
publishers_total 7.0
```

**Number of records included per Publisher**

Result is calculated by querying Document Store for distinct OAI-PMH base url values in source documents. Only values which are direct sources are included. Logically deleted records are included. The result is categorized by publisher base url.

Response body example:

```
# HELP publishers_counts Number of records included per Publisher
# TYPE publishers_counts gauge
publishers_counts{publisher="http://services.fsd.tuni.fi/v0/oai"} 2.0
publishers_counts{publisher="https://www.da-ra.de/oaip"} 1.0
publishers_counts{publisher="http://harvester.sodanet.gr:8080/oai/request"} 1.0
publishers_counts{publisher="http://oai.unidata.unimib.it/v0/oai"} 3.0
publishers_counts{publisher="http://another.url"} 1.0
publishers_counts{publisher="http://third.url"} 1.0
publishers_counts{publisher="https://data.aussda.at/oai"} 1.0
```

**Total number of records included**

Result is calculated by counting the overall number of Study records in Document Store. Logically deleted records are included.

Response body example:

```
# HELP records_total Total number of records included
# TYPE records_total gauge
records_total 10.0
```

**Number of external catalogue requests received per Aggregator**

If I understand correctly, the above should read "... per harvester". This number is incremented every time a HTTP request to OAI-PMH endpoint (`http://<host>:<port>/v0/oai`) is responded to. Harvesters are distinquished by User-Agent HTTP header.

Response body example:

```
# HELP external_catalogue_requests_per_harvester_total Number of external catalogue requests received per harvester
# TYPE external_catalogue_requests_per_harvester_total counter
external_catalogue_requests_per_harvester_total{harvester="Some Harvester"} 2.0
external_catalogue_requests_per_harvester_total{harvester="curl/7.68.0"} 1.0
```

**Total number of external catalogue requests received**

This number is incremented every time a HTTP request to OAI-PMH endpoint is responded to.

Response body example:

```
# HELP external_catalogue_requests_total Total number of external catalogue requests received
# TYPE external_catalogue_requests_total counter
external_catalogue_requests_total 3.0
```

**Number of successful external catalogue requests**

This number is incremented every time a HTTP request to OAI-PMH endpoint gets a response where HTTP status code is less than 300.

Response body example:

```
# HELP successful_catalogue_requests_total Number of successful external catalogue requests
# TYPE successful_catalogue_requests_total counter
successful_catalogue_requests_total 3.0
```

**Number of unsuccessful external catalogue requests**

This number is incremented every time a HTTP request to OAI-PMH endpoint gets a response where HTTP status code is greater than or equal to 300.

```
# HELP unsuccessful_catalogue_requests_total Number of unsuccessful external catalogue requests
# TYPE unsuccessful_catalogue_requests_total counter
unsuccessful_catalogue_requests_total 0.0
```

### I have not implemented the following metrics:

**Inclusion success rate per Publisher**
**Inclusion failure rate per Publisher**
**Average inclusion success rate**
**Average inclusion failure rate**

The above metrics require that the component gathering the numbers should know if a source records is not included in the aggregator. I cannot get such information from the OAI-PMH Repo Handler component. I think some other component could compare the metrics from the OAI-PMH Repo Handler ("Number of records included per Publisher" -metric) and number of records harvested by CESSDA harvester.

**Number of publishers requested**

How should this be calculated?

I have the HTTP request and response properties I can use to calculate metrics values. I can also make queries to Document Store. I don't think this can be calculated by queries or http properties.

**Average time taken to harvest records from an external catalogue request**

How should this be calculated? Should I calculate the average response time to verb=ListRecords or to verb=GetRecord? Or should I calculate the overall time it takes for a full harvest using ListRecords verb. I might be able to calculate something based on HTTP User Agent & resumptionToken values, but that might be a bit complex to do.


Any thoughts on the implementation details of the Service Provider metrics? Should the logically deleted records be excluded from the numbers?
What about the HTTP Request metrics? Is the HTTP status code good for determining which is a successful request or should I use something else? For example OAI Error responses all return status code 200 (https://datacatalogue.cessda.eu/oai-pmh/v0/oai?verb=invalid).

Any other feedback is also welcome.

I will continue by adding tests against the integration of prometheus client & aggregator. I will make changes to metrics implementation next week, if needed.

**Comment by matthew-morris-cessda** [comment]
@Joshocan Could you take a look?

Toni, I'll provide some feedback of my own soon.

**Comment by matthew-morris-cessda** [comment]
As requested, here is some feedback.

## Number of records included

These currently include records marked as deleted. I think there should be a corresponding metric without logically deleted records.

## Number of external catalogue requests received per Aggregator

This is a generic metric for the amount of requests made to the OAI-PMH endpoint. There isn't any way to determine if these requests came from an aggregator. I don't think the name is quite right though, to me `requests_per_user_agent` and renaming `harvester` to `user_agent` would be better.

## Total number of external catalogue requests received

I think the names should be simplified 

- `external_catalogue_requests_total ` → `requests_total`
- `successful_catalogue_requests_total` → `requests_succeeded`
- `unsuccessful_catalogue_requests_total` → `requests_failed`

This also means that these metrics group when sorted alphabetically.

## Inclusion statistics

These metrics should be part of the aggregator client.

- Inclusion success rate per Publisher
- Inclusion failure rate per Publisher
- Average inclusion success rate
- Average inclusion failure rate

The best place for these to be emitted would be as summary logs at the end of a run (preferably in cases of abnormal termination in a best-effort basis as well).

## Number of publishers requested

I agree, @Joshocan could you clarify this?

## Average time taken to harvest records from an external catalogue request

This could mean average response time, grouped by OAI-PMH verb (i.e. one for `ListRecords`, one for `GetRecord`). I'm not sure about tracking the time it takes for a client to traverse an entire `ListRecord` chain as this seems like a lot of state to keep track of for what is supposed to be non-intrusive (in a performance sense) metrics.

**Comment by Joshocan** [comment]
Thank you @toni-sissala  for the work. These are feedback: 

### Number of publishers requested
Yes, you are right, apart from implementation difficulties, I am sure if this metrics is relevant. I recommend we drop it.

### Number of external catalogue requests received per Aggregator
I agree with @matthew-morris-cessda Request can come from anywhere other than aggregator or harvester. "user-agent" is more appropriate. 

> I have not implemented the following metrics:
> Inclusion success rate per Publisher
> Inclusion failure rate per Publisher
> Average inclusion success rate
> Average inclusion failure rate
We can proceed without these for now. 

Apart from these, I think some of the metrics are quite redundant for instance: 
We can get Total number of records included from Number of records included per Publisher 
sum (publishers_counts) = records_total
However, we can them as they are.

**Comment by toni-sissala** [comment]
Thanks for the feedback! I now have all the info I need to get this implemented.

**Comment by toni-sissala** [comment]
Here is a status update and some exceptions I have made to the requested implementation. Let me know what you think.

> As requested, here is some feedback.
> 
> ## Number of records included
> These currently include records marked as deleted. I think there should be a corresponding metric without logically deleted records.

I have added metric for total number of records without deleted (`records_total_without_deleted`) and number of records included for each publisher without logically deleted records (`publishers_counts_without_deleted`).

Example records_total_without_deleted:

```
# HELP records_total_without_deleted Total number of records included without logically deleted records
# TYPE records_total_without_deleted gauge
records_total_without_deleted 1.0
```

Example publishers_counts_without_deleted:

```
# HELP publishers_counts_without_deleted Number of records included per Publisher without logically deleted records
# TYPE publishers_counts_without_deleted gauge
publishers_counts_without_deleted{publisher="http://services.fsd.tuni.fi/v0/oai"} 0.0
publishers_counts_without_deleted{publisher="https://www.da-ra.de/oaip"} 0.0
publishers_counts_without_deleted{publisher="http://harvester.sodanet.gr:8080/oai/request"} 0.0
publishers_counts_without_deleted{publisher="http://oai.unidata.unimib.it/v0/oai"} 0.0
publishers_counts_without_deleted{publisher="http://another.url"} 0.0
publishers_counts_without_deleted{publisher="http://third.url"} 0.0
publishers_counts_without_deleted{publisher="https://data.aussda.at/oai"} 1.0
```

> 
> ## Number of external catalogue requests received per Aggregator
> This is a generic metric for the amount of requests made to the OAI-PMH endpoint. There isn't any way to determine if these requests came from an aggregator. I don't think the name is quite right though, to me `requests_per_user_agent` and renaming `harvester` to `user_agent` would be better.
> 

I have renamed this to `requests_per_user_agent_total`.

> ## Total number of external catalogue requests received
> I think the names should be simplified
> 
> * `external_catalogue_requests_total ` → `requests_total`
> * `successful_catalogue_requests_total` → `requests_succeeded`
> * `unsuccessful_catalogue_requests_total` → `requests_failed`
> 
> This also means that these metrics group when sorted alphabetically.

I have simplified these names. However, the prometheus client adds a suffix `_total` to every counter (https://github.com/prometheus/client_python#counter). If this needs to change, I need to fork the prometheus client and make changes to its internal logic. There is no way to tell the client not to add such suffix.

> 
> ## Average time taken to harvest records from an external catalogue request
> This could mean average response time, grouped by OAI-PMH verb (i.e. one for `ListRecords`, one for `GetRecord`). I'm not sure about tracking the time it takes for a client to traverse an entire `ListRecord` chain as this seems like a lot of state to keep track of for what is supposed to be non-intrusive (in a performance sense) metrics.

I have added a summary metrics that sums up response times in milliseconds by OAI verb and requested metadataPrefix. It also outputs the count of these requests, so the average time can be calculated from this metric. The prometheus client does not support counting the average out-of-the-box. I think I could create a custom metric that counts the average, but have not looked at that yet. Here is how this works currently:

```
# first request
$ curl "localhost:5003/v0/oai?verb=ListRecords&metadataPrefix=oai_dc"
[...]
# second request to same list
$ curl "localhost:5003/v0/oai?verb=ListRecords&metadataPrefix=oai_dc"
[...]
# third request to another list
$ curl "localhost:5003/v0/oai?verb=ListRecords&metadataPrefix=oai_ddi25"
[...]
# request_duration metrics
$ curl localhost:5003/metrics
# HELP requests_duration Response time in milliseconds
# TYPE requests_duration summary
requests_duration_count{metadataPrefix="oai_dc",verb="ListRecords"} 2.0
requests_duration_sum{metadataPrefix="oai_dc",verb="ListRecords"} 199.04565811157227
requests_duration_count{metadataPrefix="oai_ddi25",verb="ListRecords"} 1.0
requests_duration_sum{metadataPrefix="oai_ddi25",verb="ListRecords"} 119.09246444702148
[...]
```

If these exceptions to the requested metrics are OK, then I will mark the PR ready and request review.

**Comment by matthew-morris-cessda** [comment]
Regarding the "Total number of external catalogue requests received" metrics, given the limitation of always having `_total` appended I would keep the names as follows:

- `external_catalogue_requests_total` → `requests_total`
- `successful_catalogue_requests_total` → `requests_succeeded_total`
- `unsuccessful_catalogue_requests_total` → `requests_failed`_total`

Apart from this, all seems fine and I think it would be better to merge so testing can begin. We can always make modifications later.

**Comment by toni-sissala** [comment]
Thanks Matthew! I will mark the PR ready and request review.
