### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.aggregator.oai-pmh-repo-handler#8]
**Original report on BitBucket by CESSDA Support Team (GitHub: [cessda](https://github.com/cessda)).**

----------------------------------------

This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

---

### ⚠ Dependency Lookup Warnings ⚠

-   Renovate failed to look up the following dependencies: `kuha_common`, `kuha_oai_pmh_repo_handler`, `cdcagg_common`.

Files affected: `setup.py`

---

## Open

These updates have all been created already.

 - [Update dependency kuha_common to v2.1.0](../../pull-requests/50)
 - [Update python Docker tag to v3.11](../../pull-requests/43)

## Detected dependencies

**dockerfile**

**Dockerfile**

 - `python 3.9-slim`
 - `python 3.9-slim`

**pip_requirements**

**requirements.txt**

 - `tornado ==6.2.0`
 - `ConfigArgParse ==1.5.3`
 - `py12flogging ==0.5.0`
 - `six ==1.16.0`
 - `Genshi ==0.7.7`
 - `PyYAML ==6.0.0`
 - `kuha_common 2.0.1`
 - `kuha_oai_pmh_repo_handler 1.2.0`

**pip_setup**

**setup.py**

 - `kuha_common >=2.0.0`
 - `kuha_oai_pmh_repo_handler >=1.2.0`
 - `cdcagg_common >=0.5.0`

**Comment by matthew-morris-cessda** [comment]
Dependabot is no longer being used on this repository
